sudo: required
dist: trusty
language: cpp

script:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update
- sudo apt-get install -y libgtest-dev cmake gcc-7 g++-7
- builddir=$(pwd)
- cd /usr/src/gtest
- sudo cmake .
- sudo cmake --build .
- sudo cp *.a /usr/lib
- cd $builddir
- mkdir -p bin
- cd bin
- sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
- sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-7 /usr/bin/g++
- g++ --version
- cmake ..
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- cd ..

deploy:
- provider: script
  skip_cleanup: true
  script:
  - curl -T bin/otus-async-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uyukigaru:$BINTRAY_API_KEY "https://api.bintray.com/content/yukigaru/otus-bin/otus-async/$TRAVIS_BUILD_NUMBER/otus-async-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
